---
- name: Prepare Apache web server with custom index file
  hosts: node
  become: yes
  become_user: root
  tasks:
    - name: install apache
	    yum: name=httpd state=latest
	  
	  - name: copy index file
	    ansible.builtin.copy:
	      src: /tmp/index.html
		    dest: /var/www/html/
